version: "3.9"  # optional since v1.27.0
services:
  server:
    image: areskiko/easee_status

    # Needed to pass username and password if not set as environment variables
    tty: true
    stdin_open: true

    # Easier access to logs
    volumes:
      - logVolume:/var/log/
      # - credentialVolume:/credentials/
    
    # Settings
    environment:
      # Required variables
      - INFLUXDB_ADDR=http://localhost:8086
      - INFLUXDB_DB_NAME=MyDatabase
      # Optional variables
      # - LOG_LEVEL=info # defaults to info
      # - CREDENTIALS_FILE=/credentials/credentials
      # Update interval, measured in minutes. 
      # - INTERVAL=1 # defaults to 1
      # - USERNAME=admin
      # - PASSWORD=admin

volumes:
  # credentials: {}
  logvolume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/CasaMack/easee_status'
