name: Publish Docker image latest arm

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry_arm:
    name: Push Docker image to Docker Hub for arm
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - 
        name: Workaround
        run: |
          # Workaround for https://github.com/rust-lang/cargo/issues/8719
          sudo mkdir -p /var/lib/docker
          sudo mount -t tmpfs -o size=14G none /var/lib/docker
          sudo systemctl restart docker
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: areskiko/easee_status:arm